services:
  docksync:
    environment:
      RCLONE_CONFIG_PASS_FILE: /run/secrets/rclone_config_pass
      ERROR_WEBHOOK_URL_FILE: /run/secrets/docksync_error_webhook
    secrets:
      - rclone_config_pass
      - docksync_error_webhook

secrets:
  rclone_config_pass:
    file: ./secrets/rclone_config_pass
  docksync_error_webhook:
    file: ./secrets/docksync_error_webhook
